M48
; DRILL file {KiCad (7.0.0)} date Sun Jul  9 18:50:53 2023
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2023-07-09T18:50:53+02:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(7.0.0)
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C3.200
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C4.000
%
G90
G05
T1
X104.75Y-89.9
X225.3Y-71.425
X225.3Y-108.225
T2
X163.2Y-89.9
T0
M30
