M48
; DRILL file {KiCad (7.0.0)} date Wed Sep 27 17:19:53 2023
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2023-09-27T17:19:53+02:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(7.0.0)
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C3.200
%
G90
G05
T1
X100.0Y-100.0
X130.0Y-155.0
X160.0Y-155.0
X190.0Y-100.0
T0
M30
